### ISSUE TITLE
Fix link to schedule on gh-pages site

### ISSUE THREAD

**Issue by stephwright** [mozillascience/WOW-2017#11]
Link on github.io website (https://mozillascience.github.io/WOW-2017/#schedule)
in first sentence under Schedule points to 2016 repo (https://github.com/mozillascience/working-open-workshop/blob/gh-pages/wow-schedule.md)

Do we have a new schedule in this repo?

**Comment by auremoser** [comment]
Good catch, yes it's available [here](https://science.mozilla.org/programs/events/working-open-workshop-march-2017/schedule). I just fixed the link.

Thanks!

**Comment by stephwright** [comment]
👍
