### ISSUE TITLE
Issue linking data_rescue_exercise

### ISSUE THREAD

**Issue by daniellecrobinson** [mozillascience/WOW-2017#13]
Hey! I am having trouble linking data_rescue_exercise in the main index file....

**Comment by daniellecrobinson** [comment]
line 84 of the index.html file...


Changed link in index.html to "../data_rescue_exercise/data_rescue_exercise.html"

get a 404 page

**Comment by daniellecrobinson** [comment]
I legit can't figure this out 👎

**Comment by daniellecrobinson** [comment]
also, I can't figure out how to make my JSON file pretty in the hmtl - any hints?

https://htmlpreview.github.io/?https://github.com/mozillascience/WOW-2017/blob/master/data_rescue_exercise/data_rescue_exercise.html

**Comment by ha0ye** [comment]
I think I have a fix - please check my PR.

**Comment by daniellecrobinson** [comment]
Thanks @ha0ye - it's still not working for me... maybe it's a browser cache thing? Does it link out for you? I also changed it to 
```
href="data_rescue_exercise/"
```
 which mirrors 
```
href="personas_pathways/"
```
 in the line above it... personas_pathways seems to work fine.

**Comment by ha0ye** [comment]
If there's no specified html file, it will default to `index.html`, which is the name in the `personas_pathways` path. So I think you either want to rename the html file or set the link to the full path, so that it resolves into `https://mozillascience.github.io/WOW-2017/data_rescue_exercise/data_rescue_exercise.html`

**Comment by daniellecrobinson** [comment]
Ah, ok, I changed it... hopefully it works :)

**Comment by daniellecrobinson** [comment]
THANKS @ha0ye it works now!!

**Comment by auremoser** [comment]
Thanks @ha0ye + @daniellecrobinson , I'm sorry I didn't get these automated alerts. :(

**Comment by daniellecrobinson** [comment]
And thanks for formatting the JSON with the <pre> ! It looks so much better now! @ha0ye 
No worried @auremoser

**Comment by auremoser** [comment]
It looks very nice @ha0ye, thank you, I just updated one of the images and added some `<strong>` text, feel free to change @daniellecrobinson !
